### ISSUE TITLE
Warning after upgrading to Flutter 3.0.0

### ISSUE THREAD

**Issue by pst9354** [koukibadr/Motion-Toast#64] opened 2022-05-13 07:35 UTC
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/lib/motion_toast.dart:499

**Comment by koukibadr** [comment] 2022-05-13 07:37
thanks @pst9354 for filling this issue I will work on it

**Comment by koukibadr** [comment] 2022-05-25 21:47
The issue is fixed in the newer version 2.1.7 check it out

**Comment by pires22** [comment] 2022-06-03 23:27
Issue was fixed in 2.1.7 but apparently 2.1.8 gave another issue:

C:/Flutter/.pub-cache/hosted/pub.dartlang.org/motion_toast-2.1.8/lib/motion_toast.dart:499:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/Flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
WidgetsBinding.instance.addPostFrameCallback()

If I use version 2.1.7 there is no issues.
I didn't want to open another issue because I think it's related.
@koukibadr

**Comment by koukibadr** [comment] 2022-06-04 20:54
Thanks for sending me this issue @pires22 
I will check it out

**Comment by koukibadr** [comment] 2022-06-05 07:16
@pires22 I just published a new version 2.1.9 check it out 
[https://pub.dev/packages/motion_toast](https://pub.dev/packages/motion_toast)

**Comment by pires22** [comment] 2022-06-08 14:05
@koukibadr everything working fine now, thank you!

**Closed** 2022-06-12 16:36 UTC
Labels: bug
